# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
# flake8: noqa

# generated by datamodel-codegen:
#   filename:  https://raw.githubusercontent.com/compose-spec/compose-spec/master/schema/compose-spec.json
#   timestamp: 2024-04-22T07:58:32+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Cgroup(Enum):
    HOST = "host"
    PRIVATE = "private"


class CredentialSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    config: str | None = None
    file: str | None = None
    registry: str | None = None


class Condition(Enum):
    SERVICE_STARTED = "service_started"
    SERVICE_HEALTHY = "service_healthy"
    SERVICE_COMPLETED_SUCCESSFULLY = "service_completed_successfully"


class DependsOn(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    restart: bool | None = None
    required: bool | None = True
    condition: Condition


class Extends(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    service: str
    file: str | None = None


class Logging(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    driver: str | None = None
    options: dict[str, str | float | None] | None = None


class Ports(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    mode: str | None = None
    host_ip: str | None = None
    target: int | None = None
    published: str | int | None = None
    protocol: str | None = None
    app_protocol: str | None = None


class PullPolicy(Enum):
    ALWAYS = "always"
    NEVER = "never"
    IF_NOT_PRESENT = "if_not_present"
    BUILD = "build"
    MISSING = "missing"


class Selinux(Enum):
    Z = "z"
    z_1 = "Z"


class Bind(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    propagation: str | None = None
    create_host_path: bool | None = None
    selinux: Selinux | None = None


class Volume1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    nocopy: bool | None = None
    subpath: str | None = None


class Size(RootModel[int]):
    root: int = Field(..., ge=0)


class Tmpfs(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    size: Size | str | None = None
    mode: float | None = None


class Volumes(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    type: str
    source: str | None = None
    target: str | None = None
    read_only: bool | None = None
    consistency: str | None = None
    bind: Bind | None = None
    volume: Volume1 | None = None
    tmpfs: Tmpfs | None = None


class Healthcheck(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    disable: bool | None = None
    interval: str | None = None
    retries: float | None = None
    test: str | list[str] | None = None
    timeout: str | None = None
    start_period: str | None = None
    start_interval: str | None = None


class Action(Enum):
    REBUILD = "rebuild"
    SYNC = "sync"
    SYNC_RESTART = "sync+restart"


class WatchItem(BaseModel):
    ignore: list[str] | None = None
    path: str | None = None
    action: Action | None = None
    target: str | None = None


class Development(BaseModel):
    watch: list[WatchItem] | None = None


class Order(Enum):
    START_FIRST = "start-first"
    STOP_FIRST = "stop-first"


class RollbackConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    parallelism: int | None = None
    delay: str | None = None
    failure_action: str | None = None
    monitor: str | None = None
    max_failure_ratio: float | None = None
    order: Order | None = None


class UpdateConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    parallelism: int | None = None
    delay: str | None = None
    failure_action: str | None = None
    monitor: str | None = None
    max_failure_ratio: float | None = None
    order: Order | None = None


class Limits(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cpus: float | str | None = None
    memory: str | None = None
    pids: int | None = None


class RestartPolicy(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    condition: str | None = None
    delay: str | None = None
    max_attempts: int | None = None
    window: str | None = None


class Preference(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    spread: str | None = None


class Placement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    constraints: list[str] | None = None
    preferences: list[Preference] | None = None
    max_replicas_per_node: int | None = None


class DiscreteResourceSpec(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: str | None = None
    value: float | None = None


class GenericResource(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    discrete_resource_spec: DiscreteResourceSpec | None = None


class GenericResources(RootModel[list[GenericResource]]):
    root: list[GenericResource]


class ConfigItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subnet: str | None = None
    ip_range: str | None = None
    gateway: str | None = None
    aux_addresses: dict[str, str] | None = None


class Ipam(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    driver: str | None = None
    config: list[ConfigItem] | None = None
    options: dict[str, str] | None = None


class External(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None


class External2(BaseModel):
    name: str | None = None


class Command(RootModel[str | list[str] | None]):
    root: str | list[str] | None


class EnvFile1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str
    required: bool | None = True


class EnvFile(RootModel[str | list[str | EnvFile1]]):
    root: str | list[str | EnvFile1]


class ListOfStrings(RootModel[list[str]]):
    root: list[str]


class ListOrDict1(RootModel[list[Any]]):
    root: list[Any]


class ListOrDict(
    RootModel[dict[str, str | float | bool | None] | ListOrDict1]
):
    root: dict[str, str | float | bool | None] | ListOrDict1


class BlkioLimit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str | None = None
    rate: int | str | None = None


class BlkioWeight(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: str | None = None
    weight: int | None = None


class ServiceConfigOrSecret1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    source: str | None = None
    target: str | None = None
    uid: str | None = None
    gid: str | None = None
    mode: float | None = None


class ServiceConfigOrSecret(RootModel[list[str | ServiceConfigOrSecret1]]):
    root: list[str | ServiceConfigOrSecret1]


class Ulimits1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hard: int
    soft: int


class Ulimits(RootModel[dict[str, int | Ulimits1]]):
    root: dict[str, int | Ulimits1]


class Constraints(RootModel[Any]):
    root: Any


class Build(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    context: str | None = None
    dockerfile: str | None = None
    dockerfile_inline: str | None = None
    entitlements: list[str] | None = None
    args: ListOrDict | None = None
    ssh: ListOrDict | None = None
    labels: ListOrDict | None = None
    cache_from: list[str] | None = None
    cache_to: list[str] | None = None
    no_cache: bool | None = None
    additional_contexts: ListOrDict | None = None
    network: str | None = None
    pull: bool | None = None
    target: str | None = None
    shm_size: int | str | None = None
    extra_hosts: ListOrDict | None = None
    isolation: str | None = None
    privileged: bool | None = None
    secrets: ServiceConfigOrSecret | None = None
    tags: list[str] | None = None
    ulimits: Ulimits | None = None
    platforms: list[str] | None = None


class BlkioConfig(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    device_read_bps: list[BlkioLimit] | None = None
    device_read_iops: list[BlkioLimit] | None = None
    device_write_bps: list[BlkioLimit] | None = None
    device_write_iops: list[BlkioLimit] | None = None
    weight: int | None = None
    weight_device: list[BlkioWeight] | None = None


class Networks(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    aliases: ListOfStrings | None = None
    ipv4_address: str | None = None
    ipv6_address: str | None = None
    link_local_ips: ListOfStrings | None = None
    mac_address: str | None = None
    priority: float | None = None


class Device(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    capabilities: ListOfStrings | None = None
    count: str | int | None = None
    device_ids: ListOfStrings | None = None
    driver: str | None = None
    options: ListOrDict | None = None


class Devices(RootModel[list[Device]]):
    root: list[Device]


class Network(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    driver: str | None = None
    driver_opts: dict[str, str | float] | None = None
    ipam: Ipam | None = None
    external: External | None = None
    internal: bool | None = None
    enable_ipv6: bool | None = None
    attachable: bool | None = None
    labels: ListOrDict | None = None


class Volume(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    driver: str | None = None
    driver_opts: dict[str, str | float] | None = None
    external: External | None = None
    labels: ListOrDict | None = None


class Secret(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    environment: str | None = None
    file: str | None = None
    external: External2 | None = None
    labels: ListOrDict | None = None
    driver: str | None = None
    driver_opts: dict[str, str | float] | None = None
    template_driver: str | None = None


class Config(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str | None = None
    content: str | None = None
    environment: str | None = None
    file: str | None = None
    external: External2 | None = None
    labels: ListOrDict | None = None
    template_driver: str | None = None


class StringOrList(RootModel[str | ListOfStrings]):
    root: str | ListOfStrings


class Reservations(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    cpus: float | str | None = None
    memory: str | None = None
    generic_resources: GenericResources | None = None
    devices: Devices | None = None


class Resources(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    limits: Limits | None = None
    reservations: Reservations | None = None


class Deployment(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    mode: str | None = None
    endpoint_mode: str | None = None
    replicas: int | None = None
    labels: ListOrDict | None = None
    rollback_config: RollbackConfig | None = None
    update_config: UpdateConfig | None = None
    resources: Resources | None = None
    restart_policy: RestartPolicy | None = None
    placement: Placement | None = None


class Include1(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    path: StringOrList | None = None
    env_file: StringOrList | None = None
    project_directory: str | None = None


class Include(RootModel[str | Include1]):
    root: str | Include1


class Service(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    develop: Development | None = None
    deploy: Deployment | None = None
    annotations: ListOrDict | None = None
    attach: bool | None = None
    build: str | Build | None = None
    blkio_config: BlkioConfig | None = None
    cap_add: list[str] | None = None
    cap_drop: list[str] | None = None
    cgroup: Cgroup | None = None
    cgroup_parent: str | None = None
    command: Command | None = None
    configs: ServiceConfigOrSecret | None = None
    container_name: str | None = None
    cpu_count: int | None = Field(None, ge=0)
    cpu_percent: int | None = Field(None, ge=0, le=100)
    cpu_shares: float | str | None = None
    cpu_quota: float | str | None = None
    cpu_period: float | str | None = None
    cpu_rt_period: float | str | None = None
    cpu_rt_runtime: float | str | None = None
    cpus: float | str | None = None
    cpuset: str | None = None
    credential_spec: CredentialSpec | None = None
    depends_on: ListOfStrings | dict[str, DependsOn] | None = None
    device_cgroup_rules: ListOfStrings | None = None
    devices: list[str] | None = None
    dns: StringOrList | None = None
    dns_opt: list[str] | None = None
    dns_search: StringOrList | None = None
    domainname: str | None = None
    entrypoint: Command | None = None
    env_file: EnvFile | None = None
    environment: ListOrDict | None = None
    expose: list[str | float] | None = None
    extends: str | Extends | None = None
    external_links: list[str] | None = None
    extra_hosts: ListOrDict | None = None
    group_add: list[str | float] | None = None
    healthcheck: Healthcheck | None = None
    hostname: str | None = None
    image: str | None = None
    init: bool | None = None
    ipc: str | None = None
    isolation: str | None = None
    labels: ListOrDict | None = None
    links: list[str] | None = None
    logging: Logging | None = None
    mac_address: str | None = None
    mem_limit: float | str | None = None
    mem_reservation: str | int | None = None
    mem_swappiness: int | None = None
    memswap_limit: float | str | None = None
    network_mode: str | None = None
    networks: ListOfStrings | dict[str, Networks | None] | None = None
    oom_kill_disable: bool | None = None
    oom_score_adj: int | None = Field(None, ge=-1000, le=1000)
    pid: str | None = None
    pids_limit: float | str | None = None
    platform: str | None = None
    ports: list[float | str | Ports] | None = None
    privileged: bool | None = None
    profiles: ListOfStrings | None = None
    pull_policy: PullPolicy | None = None
    read_only: bool | None = None
    restart: str | None = None
    runtime: str | None = None
    scale: int | None = None
    security_opt: list[str] | None = None
    shm_size: float | str | None = None
    secrets: ServiceConfigOrSecret | None = None
    sysctls: ListOrDict | None = None
    stdin_open: bool | None = None
    stop_grace_period: str | None = None
    stop_signal: str | None = None
    storage_opt: dict[str, Any] | None = None
    tmpfs: StringOrList | None = None
    tty: bool | None = None
    ulimits: Ulimits | None = None
    user: str | None = None
    uts: str | None = None
    userns_mode: str | None = None
    volumes: list[str | Volumes] | None = None
    volumes_from: list[str] | None = None
    working_dir: str | None = None


class ComposeSpecification(BaseModel):
    """
    The Compose file is a YAML file defining a multi-containers based application.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    version: str | None = None
    """
    declared for backward compatibility, ignored.
    """
    name: str | None = Field(None, pattern="^[a-z0-9][a-z0-9_-]*$")
    """
    define the Compose project name, until user defines one explicitly.
    """
    include: list[Include] | None = None
    """
    compose sub-projects to be included.
    """
    services: dict[str, Service] | None = None
    networks: dict[str, Network | None] | None = None
    volumes: dict[str, Volume | None] | None = None
    secrets: dict[str, Secret] | None = None
    configs: dict[str, Config] | None = None
