---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-json
        exclude: ^\.(vscode|devcontainer)
      - id: pretty-format-json
        args: [--autofix]
        exclude: ^\.(vscode|devcontainer|ipynb)
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
      - id: black-jupyter

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8

  - repo: https://github.com/fsfe/reuse-tool
    rev: v1.0.0
    hooks:
      - id: reuse

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v3.0.1
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/hadolint/hadolint
    rev: 024fd64
    hooks:
      - id: hadolint-docker
        args:
          - --ignore=DL3008
          - --ignore=DL3059

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.23.0
    hooks:
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
    - id: mypy
      additional_dependencies:
      - types-pyyaml==6.0.12.20240311
      - types-python-slugify==8.0.2.20240310
      - pandas-stubs==2.2.1.240316
