---

services:
  minio:
    image: minio/minio:RELEASE.2023-04-28T18-11-17Z
    command: server
      --address ":9000"
      --console-address ":9001"
      /data
    environment:
    - MINIO_ROOT_USER=${S3_USER}
    - MINIO_ROOT_PASSWORD=${S3_PASSWORD}
    ports:
    - target: 9000
      published: 9000
      protocol: tcp
      mode: host
    - target: 9001
      published: 9001
      protocol: tcp
      mode: host
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 20s
      retries: 3
      start_period: 20s
    volumes:
    - type: bind
      source: ./data/minio/
      target: /data/

  mosquitto:
    image: eclipse-mosquitto:2
    volumes:
    - type: bind
      source: ./etc/mosquitto/
      target: /mosquitto/config/
    - type: bind
      source: ./log/mosquitto/
      target: /mosquitto/log/
    - type: bind
      source: ./data/mosquitto/
      target: /mosquitto/data/
    ports:
    - target: 1883
      published: 1883
      protocol: tcp
      mode: host
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-p", "1880", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck", "-W", "3"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 10s

  configure-minio:
    image: minio/mc:RELEASE.2023-05-04T18-10-16Z
    depends_on:
    - minio
    env_file:
    - .env
    entrypoint: /bin/sh /setup.sh
    volumes:
    - type: bind
      source: ./etc/minio/setup.sh
      target: /setup.sh