---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

services:
  scheduler:
    build:
      context: .

    command: ["scheduler"]

  demo-data:
    build:
      context: .

    command: ["demo-data"]
