---
# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

triggers:
  initial-startup:
    type: startup

  when-acls-changed:
    type: created
    prefix: config/acls/

  regular-reconciliation:
    type: schedule
    unit: hours
    interval: 1

container:
  image: seguro/platform
  command: ["acl-syncer"]
