---
# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

container:
  image: seguro/platform

  environment:
    RATE: "10.0"
    BLOCK_INTERVAL: "1m"
    SAMPLE_TYPE: "measurement"
    TOPIC: data/measurements/demo-data
    DEBUG: True

  command: ["demo-data"]
