---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

triggers: [] # Disabled

container:
  image: seguro/platform

  command: ["demo-data"]

  env_file:
    - .env
