---
# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

container:
  image: seguro/platform

  environment:
    RATE: "10.0"
    VALUES: "6"
    BLOCK_INTERVAL: "1m"
    TOPIC: data/measurements/mp1

  command: ["demo-data"]
