---
# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

build: true

triggers:
  new-data:
    type: created
    prefix: XXX

container:
  build:
    context: ./images/examples/job-worker
