---
# SPDX-FileCopyrightText: 2025 Lukas Lenz, RWTH Aachen
# SPDX-License-Identifier: Apache-2.0

container:
  image: seguro/platform

  environment:
    RATE: "10.0"
    BLOCK_INTERVAL: "1m"
    SAMPLE_TYPE: "measurement"
    TOPIC: data/measurements/demo-data

  command: ["flex-marketing-service"]
