# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---

notebook: notebooks/example.ipynb

triggers:
- id: notebook-changed

  type: modified

  prefix: notebooks/

container:
  image: seguro/platform

  env_file: .env

  command: ["notebook-executor"]
