---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

notebook: notebooks/example.ipynb

triggers:
  notebook-changed:
    type: created

    prefix: notebooks/
    initial: true

container:
  image: seguro/platform
  command: ["notebook-executor"]
