# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---

container:
  image: seguro/platform

  # We require access to the MQTT_* and S3_* env vars
  env_file: .env

  command: ["recorder"]
