---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

triggers:
  - id: initial
    type: startup
  - id: every-minute
    type: schedule
    interval: 5
    unit: minutes

container:
  image: ubuntu
  command:
    - /bin/sh
    - -c
    - |
      echo "Hallo"
      date
      env
      sleep 5
      echo "Bye..."
