# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
# triggers:
# - type: schedule
#   interval: 1
#   unit: minutes

recreate: true

container:
  image: ubuntu
  command:
  - /bin/sh
  - -c
  - |
    echo "Hallo"
    date
    env
    sleep 5
    echo "Bye..."
