---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

version: 0.1

storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  s3:
    region: us-east-1
    regionendpoint: minio:9000
    forcepathstyle: true
    accelerate: false
    bucket: registry
    secure: true

auth:
  htpasswd:
    path: /keys/registry_htpasswd
    realm: basic-realm

http:
  addr: :5000
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
  tls:
    clientcas:
    - /certs/ca.crt
