---
# SPDX-FileCopyrightText: 2023 Steffen Vogel <steffen.vogel@opal-rt.com>, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

version: 0.1

storage:
  delete:
    enabled: true
  cache:
    blobdescriptor: inmemory
  s3:
    accesskey: seguro
    secretkey: stwh4herne
    region: us-east-1
    regionendpoint: minio:9000
    forcepathstyle: true
    accelerate: false
    bucket: registry
    secure: false

auth:
  htpasswd:
    path: /etc/docker/registry/htpasswd
    realm: basic-realm

http:
  addr: :5001
  headers:
    X-Content-Type-Options: [nosniff]
    Access-Control-Allow-Origin: ['http://localhost:8080']
    Access-Control-Allow-Methods: ['HEAD', 'GET', 'OPTIONS', 'DELETE']
    Access-Control-Allow-Headers: ['Authorization', 'Accept', 'Cache-Control']
    Access-Control-Max-Age: [1728000]
    Access-Control-Allow-Credentials: [true]
    Access-Control-Expose-Headers: ['Docker-Content-Digest']
  secret: Aewoh4ool9kaisaec5geiwoo8geedaig
#   tls:
#     certificate: /keys/registry.crt
#     key: /keys/registry.key
