# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0
---
triggers:
- type: schedule
  interval: 5
  unit: seconds

scale: 1

container:
  image: ubuntu
  command: /bin/sh -c "echo $(date); env; sleep 2"
  # Docker-compose compatible service definition
