---
# SPDX-FileCopyrightText: 2023-2024 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

name: Deploy Sphinx documentation to Pages

on:
  push:
    branches:
      - main

jobs:
  pages:
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Graphviz deps
        run: |
          sudo apt-get update && \
          sudo apt-get install --yes --no-install-recommends \
            graphviz \
            libgraphviz-dev \
            pkg-config

      - name: Setup Python, Poetry and Dependencies
        uses: packetcoders/action-setup-cache-python-poetry@main
        with:
          python-version: 3.11
          poetry-version: 1.7.1

      - name: Build docs
        run: poetry run sphinx-build -b html docs/ build/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build

      - name: Deploy to Pages
        id: deployment
        uses: actions/deploy-pages@v4
