---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

name: Test with Docker Compose

permissions:
  packages: write

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v2

      - name: Install Poetry
        run: pipx install poetry==1.7.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: poetry

      - name: Login to Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: poetry install --without docs

      - name: Create Docker Compose cache file
        run: poetry run python scripts/generate-compose-cache.py

      - name: Create .env file
        run: sed 's/PLEASE-CHANGE-ME/7418GOKUjD4npqnfBi3uDVsrIoqgiEJD/g' .env.example > .env

      - name: Build Docker Compose
        run: docker buildx bake
          --file compose.yaml
          --file compose-cache.json

      - name: Start containers
        run: docker compose up --detach

      - name: Ensure S3 buckets exist
        run: docker compose up minio-setup

      - name: Test with pytest
        env:
          S3_HOST: localhost
          MQTT_HOST: localhost
        run: poetry run pytest

      - name: Get Docker Compose log output
        if: always()
        run: docker compose logs | tee docker-compose.log

      - name: Archive Docker Compose logs
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: compose-logs
          path: docker-compose.log

      - name: Stop containers
        if: always()
        run: docker compose down
