---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

name: Test with Docker Compose

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  docker-compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Start containers
        run: docker compose up
          --detach
          --build

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]

      - name: Ensure S3 buckets exist
        run: docker compose up minio-setup

      - name: Test with pytest
        env:
          S3_HOST: localhost
          MQTT_HOST: localhost
        run: |
          pytest

      - name: Stop containers
        if: always()
        run: docker-compose down
