---
# SPDX-FileCopyrightText: 2023 Steffen Vogel, OPAL-RT Germany GmbH
# SPDX-License-Identifier: Apache-2.0

name: Test with Docker Compose

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  compose:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Docker builder
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Create .env file
        run: sed 's/PLEASE-CHANGE-ME/7418GOKUjD4npqnfBi3uDVsrIoqgiEJD/g' .env.example > .env

      - name: Start containers
        run: docker compose up --detach --build

      - name: Install Poetry
        run: pipx install poetry==1.7.1

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          cache: poetry

      - name: Install dependencies
        run: poetry install --without docs

      - name: Ensure S3 buckets exist
        run: docker compose up minio-setup

      - name: Test with pytest
        env:
          S3_HOST: localhost
          MQTT_HOST: localhost
        run: poetry run pytest

      - name: Stop containers
        if: always()
        run: docker compose down
